version: '3.8'

services:
  postgres:
    build:
      context: src/main/kotlin/databases/postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - kaizen-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build:
      context: src/main/kotlin/databases/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - kaizen-network

  kotlin-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - kaizen-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - ./.env

networks:
  kaizen-network:
    driver: bridge
